[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
startup_mode = "Maximized"
dynamic_title = true
opacity = 0.8
decorations = "buttonless"
  

  [window.dimensions]
  columns = 160
  lines = 80

  [window.padding]
  x = 8
  y = 8

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#a6e3a1"

[colors.footer_bar]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.selection]
text = "#1e1e2e"
background = "#f5e0dc"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"# [colors.primary]
# background = "0x1E1D2F"
# foreground = "0xD9E0EE"
#
# [colors.cursor]
# text = "0x1E1D2F"
# cursor = "0xF5E0DC"
#
# [colors.normal]
# black = "0x6E6C7E"
# red = "0xF28FAD"
# green = "0xABE9B3"
# yellow = "0xFAE3B0"
# blue = "0x96CDFB"
# magenta = "0xF5C2E7"
# cyan = "0x89DCEB"
# white = "0xD9E0EE"
#
# [colors.bright]
# black = "0x988BA2"
# red = "0xF28FAD"
# green = "0xABE9B3"
# yellow = "0xFAE3B0"
# blue = "0x96CDFB"
# magenta = "0xF5C2E7"
# cyan = "0x89DCEB"
# white = "0xD9E0EE"
#
# [[colors.indexed_colors]]
# index = 16
# color = "0xF8BD96"
#
# [[colors.indexed_colors]]
# index = 17
# color = "0xF5E0DC"
#
[general]
live_config_reload = true
