live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.normal]
family = "SFMono Nerd Font"
style = "Regular"

[window]
startup_mode = "Maximized"
dynamic_title = true
opacity = 0.8
decorations = "buttonless"
  

  [window.dimensions]
  columns = 160
  lines = 80

  [window.padding]
  x = 8
  y = 8

[colors.primary]
background = "0x1E1D2F"
foreground = "0xD9E0EE"

[colors.cursor]
text = "0x1E1D2F"
cursor = "0xF5E0DC"

[colors.normal]
black = "0x6E6C7E"
red = "0xF28FAD"
green = "0xABE9B3"
yellow = "0xFAE3B0"
blue = "0x96CDFB"
magenta = "0xF5C2E7"
cyan = "0x89DCEB"
white = "0xD9E0EE"

[colors.bright]
black = "0x988BA2"
red = "0xF28FAD"
green = "0xABE9B3"
yellow = "0xFAE3B0"
blue = "0x96CDFB"
magenta = "0xF5C2E7"
cyan = "0x89DCEB"
white = "0xD9E0EE"

[[colors.indexed_colors]]
index = 16
color = "0xF8BD96"

[[colors.indexed_colors]]
index = 17
color = "0xF5E0DC"
