#!/usr/bin/env zsh

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
ITEM_DIR="$HOME/.config/sketchybar/items"

source "$HOME/.config/sketchybar/typography.sh"
source "$HOME/.config/sketchybar/colors.sh"

source "$ITEM_DIR/bar.sh"

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/aerospace.sh"

# Center
source "$ITEM_DIR/front_app.sh"

# Right
source "$ITEM_DIR/clock.sh"
# source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/music.sh"
source "$ITEM_DIR/battery.sh"

sketchybar --update
sketchybar --trigger space_change
